repositories:
  - name: jellyfin
    url: https://jellyfin.github.io/jellyfin-helm
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: m0nsterrr
    url: ghcr.io/m0nsterrr/helm-charts
    oci: true
  - name: plankanban
    url: https://plankanban.github.io/planka/

releases:
  - name: cnpg
    namespace: cnpg-system
    createNamespace: true
    chart: cnpg/cloudnative-pg

  - name: jellyfin
    namespace: jellyfin
    createNamespace: true
    chart: jellyfin/jellyfin
    version: 3.2.0
    values:
      - values/jellyfin.yaml

  - name: homepage
    namespace: homepage
    createNamespace: true
    chart: m0nsterrr/homepage
    values:
      - values/homepage.yaml

  - name: planka
    namespace: planka
    createNamespace: true
    chart: plankanban/planka
    values:
      - values/planka.yaml
