apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/part-of: dashboard
data:
  services.yaml: |
    - Media:
        - Jellyfin:
            href: "http://10.250.163.241:30619"
            description: Media streaming
            icon: jellyfin.png
        - Immich:
            href: "http://10.250.163.241:31547"
            description: Photo backup
            icon: immich.png
    - Downloads:
        - Radarr:
            href: "http://10.250.163.241:30536"
            description: Movie management
            icon: radarr.png
        - Prowlarr:
            href: "http://10.250.163.241:30458"
            description: Indexer manager
            icon: prowlarr.png
  settings.yaml: |
    title: Homelab
    headerStyle: boxed
  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
