apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.3.0.10514-ls312
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "UTC"
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /movies
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: movies
          persistentVolumeClaim:
            claimName: radarr-movies
        - name: downloads
          persistentVolumeClaim:
            claimName: radarr-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: radarr
spec:
  type: NodePort
  selector:
    app: radarr
  ports:
    - name: webui
      port: 7878
      targetPort: 7878
