apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /srv/radarr/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-data-pv
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/storage/shared-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: radarr-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 300Gi
  volumeName: radarr-data-pv
