apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /srv/radarr/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-movies-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /srv/radarr/movies
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-downloads-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /srv/qbittorrent/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: radarr-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 200Gi
  volumeName: radarr-movies-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 100Gi
  volumeName: radarr-downloads-pv
